"""add cascade delete to receipt items

Revision ID: 27ded3f077f3
Revises: e6e9f28d81bb
Create Date: 2026-05-11 22:21:05.164333

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '27ded3f077f3'
down_revision: Union[str, Sequence[str], None] = 'e6e9f28d81bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('receipt_item_receipt_id_fkey'), 'receipt_item', type_='foreignkey')
    op.create_foreign_key(None, 'receipt_item', 'receipts', ['receipt_id'], ['id'], ondelete='CASCADE')
    op.alter_column('receipts', 'receipt_image_url',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('receipts', 'receipt_image_url',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_constraint(None, 'receipt_item', type_='foreignkey')
    op.create_foreign_key(op.f('receipt_item_receipt_id_fkey'), 'receipt_item', 'receipts', ['receipt_id'], ['id'])
    # ### end Alembic commands ###
