"""rename receipt image url to receipt image key

Revision ID: 2cad88c1a8c0
Revises: ac0281840e69
Create Date: 2026-05-12 18:36:43.827697

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2cad88c1a8c0'
down_revision: Union[str, Sequence[str], None] = 'ac0281840e69'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('receipts', sa.Column('receipt_image_key', sa.String(), nullable=True))
    op.drop_column('receipts', 'receipt_image_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('receipts', sa.Column('receipt_image_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('receipts', 'receipt_image_key')
    # ### end Alembic commands ###
